# 利用ssh登录服务器自动构建ROM并发布
name: building-rom

# 运行方式:手动，自动(每月15号3点执行)，push，pull_request，点击[start]
on:
  #push:
  #pull_request:
  schedule:
    - cron:  '0 3 5 * *'
  workflow_dispatch:
     inputs:
       rom:
         description: 'ROM(Project folder)'
         required: true
         default: 'PixelExperience'
       manifest:
         description: 'Manifest'
         required: true
         default: 'https://github.com/PixelExperience/manifest'
       branch:
         description: 'Branch'
         required: true
         default: 'twelve'
       target:
         description: 'Target(Consistent with tiffany.json file name)'
         required: true
         default: 'tiffany'
       lunch:
         description: 'Lunch(aosp,lineage...)'
         required: true
         default: 'aosp'
       variant:
         description: 'Variant(userdebug,eng...)'
         required: true
         default: 'userdebug'
       brand:
         description: 'Brand'
         required: true
         default: 'xiaomi'
       sync:
         description: 'Sync'
         required: true
         default: 'true'
       build:
         description: 'Start Building'
         required: true
         default: 'true'

jobs:
  build:
    # 只允许所有者点击[start]运行
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
      # 在$GITHUB_WORKSPACE下签出您的存储库，以便您的工作可以访问它
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create Rom folder
        uses: ./
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            echo "检查项目文件夹是否存在,不存在则创建"
            apt install jq
            shutdown -c
            if [ ! -d ${{ github.event.inputs.rom }} ]; then
                mkdir ${{ github.event.inputs.rom }}
            fi
            ls

      - name: Make Clean
        uses: ./
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            echo "检查product文件夹是否存在，不存在则跳过"
            if [ -d ${{ github.event.inputs.rom }}/out/target/product/ ]; then
                cd ${{ github.event.inputs.rom }}
                source build/envsetup.sh
                make clean
                echo "Make Clean"
            fi

      - name: Repo Sync
        if: github.event.inputs.sync == 'true'
        uses: ./
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            echo "进入${{ github.event.inputs.rom }}文件夹"
            cd ${{ github.event.inputs.rom }}
            PATH="$HOME/bin:$PATH"
            if ! [ -f ".repo/manifest.xml" ]; then
                echo "manifest.xml不存在，重新初始化"
                repo init -u ${{ github.event.inputs.manifest }} -b ${{ github.event.inputs.branch }} --depth=1
            fi
            ls
            echo "开始同步"
            SYNC_START=$(date +"%s")
            if [ -f Makefile ]; then
                rm -rf Makefile
            fi
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="<b>Syncing ${{ github.event.inputs.rom }} Start Time: </b><i>$(date +"%Y-%m-%d"-%H:%M)</i>" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTML
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
            ls
            if ! [ -f Makefile ]; then
                curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="Failed sync ${{ github.event.inputs.rom }}" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTML
                exit 1
            fi
            SYNC_END=$(date +"%s")
            DIFF=$(($SYNC_END - $SYNC_START))
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="<b>Sync ${{ steps.var.outputs.rom }} Finished Time:</b> <i>$(($DIFF / 60)) minutes and $(($DIFF % 60)) seconds</i>" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTML
            echo "同步结束"

      - id: dt
        name: Cloning device specific dependencies
        uses: ./
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            echo "Cloning device specific dependencies"
            cd ${{ github.event.inputs.rom }}
            branch="$(echo ${{ github.ref }} | sed 's#refs/heads/##')"
            wget -O ${{ github.event.inputs.target }}.json -q https://raw.githubusercontent.com/${{ github.repository }}/${branch}/${{ github.event.inputs.target }}.json
            wget -O md5.txt -q https://raw.githubusercontent.com/${{ github.repository }}/${branch}/md5.txt
            ls
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="Cloning device specific dependencies" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTML
            count=$(jq length ${{ github.event.inputs.target }}.json)
            echo $count
            for ((i=0;i<${count};i++));
            do
               repo_url=$(jq -r --argjson i $[i] '.[$i].url' ${{ github.event.inputs.target }}.json)
               echo $repo_url
               branch=$(jq -r --argjson i $[i] '.[$i].branch' ${{ github.event.inputs.target }}.json)
               echo $branch
               target=$(jq -r --argjson i $[i] '.[$i].target_path' ${{ github.event.inputs.target }}.json)
               echo $target
               rm -rf $target
               if [ ! -d $target ]; then
                   git clone -b ${branch} ${repo_url} ${target} --depth=1
               fi
            done
            rm -rf ${{ github.event.inputs.target }}.json

      - id: build
        name: Start Building
        uses: ./
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            echo "开始构建"
            cd ${{ github.event.inputs.rom }}
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="CCACHE is enabled for this build" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTML
            # check and set ccache path on envsetup
            if [ -z ${CCACHE_EXEC} ]; then
                ccache_path=$(which ccache)
                if [ ! -z "$ccache_path" ]; then
                    export CCACHE_EXEC="$ccache_path"
                    echo "ccache found and CCACHE_EXEC has been set to : $ccache_path"
                else
                    echo "ccache not found/installed!"
                fi
                export USE_CCACHE=1
                export CCACHE_DIR="$HOME/.ccache/${{ github.event.inputs.rom }}/${{ github.event.inputs.target }}"
                ccache -M 50G
                ccache -s
            fi
            if [[ "${{ github.event.inputs.build }}" == 'true' ]]; then
                curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="${{ github.event.inputs.rom }} start building" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTM
                BUILD_START=$(date +"%s")
                echo "::set-output name=build_date::$(date +%Y-%m-%d)"
                source build/envsetup.sh
                lunch ${{ github.event.inputs.lunch }}_${{ github.event.inputs.target }}-${{ github.event.inputs.variant }}
                make bacon -j$(nproc --all) 2>&1 | tee log.txt
                BUILD_END=$(date +"%s")
                DIFF=$(($BUILD_END - $BUILD_START))
            fi
            FILENAME="$(ls -lS out/target/product/${{ github.event.inputs.target }}/*.zip | head -1 | awk '{print $9}')"
            SIZE=$(du -sh ${FILENAME} | awk '{print $1}')
            MD5SUM=$(md5sum ${FILENAME} | cut -d' ' -f1)
            sed -i "s/tmp/$MD5SUM/" md5.txt
            curl -X POST -d 'access_token=77c248185d23821a02e78e750066b1981002c51f4c36df9697aad2fa18f3' -d 'title=MD5SUM' -d 'author_name=Eytan' -d '@md5.txt' "https://api.telegra.ph/createPage" -o test.json
            echo $(jq -r '.result' test.json) >>md5sum.json
            MD5SUM=$(echo $(jq -r '.url' md5sum.json))
            echo $FILENAME
            NAME="$FILENAME"
            echo "::set-output name=filename::${NAME}"
            echo "::set-output name=size::${SIZE}"
            echo "::set-output name=md5sum::${MD5SUM}"
            if [[ ! -z "${NAME}" ]]; then
                curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="<b>${{ github.event.inputs.rom }} Build Complete : </b>$((DIFF / 3600)) hour(h) $((DIFF % 3600)) minute(s) and $((DIFF % 60)) second(s)" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTML
            else
                curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="${{ github.event.inputs.rom }} Build for ${{ github.event.inputs.target }} <b>failed</b> in $((DIFF / 3600)) hour(h) $((DIFF % 3600)) minute(s) and $((DIFF % 60)) second(s)!" -d chat_id=${{ secrets.CHATID }} -d parse_mode=HTML
                curl -s https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument -F document=@"log.txt" -F chat_id=${{ secrets.CHATID }}
                exit 1
            fi
            if [ -f log.txt ]; then
                rm -rf log.txt
            fi
            shutdown -h +15 &

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: 
          name: ${{ github.event.inputs.rom }}/${{ steps.build.outputs.filename }}
          tag_name: ${{ github.run_id }}
          body: ${{ github.event.inputs.rom }} built by Eytan
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}

      - id: wetrans
        name: Upload to WeTransfer
        run: |
          cd ${{ github.event.inputs.rom }}
          curl -fsSL git.io/file-transfer | sh
          wetrans=$(./transfer wet -s -p 16 --no-progress ${{ steps.build.outputs.filename }})
          wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
          echo "WeTransfer: $wetrans"
          echo "::set-output name=wetransfer::$wetrans"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d text="WeTransfer upload success" -d chat_id=${{ secrets.CHATID }} -d parse_mode=Markdown

      - name: Telegram Notification
        uses: ./
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            echo "Telegram Notification"
            if [[ ! -z "$(grep -rn "TARGET_COPY_OUT_VENDOR := vendor" ${{ steps.pwd.outputs.pwd }}/device/${{ github.event.inputs.brand }})" ]]; then
                TREBLE="#Treble"
            else
                TREBLE="#NonTreble"
            fi
            branch=$(echo ${{ github.ref }} | sed 's#refs/heads/##')
            echo $branch
            BANNER_LINK="https://raw.githubusercontent.com/${{ github.repository }}/${branch}/logo/${{ github.event.inputs.rom }}.png"
            echo "$BANNER_LINK"
            if ! [ -d "$HOME/logo" ]; then
                mkdir "$HOME/logo"
            fi
            BANNER="$HOME/logo/${{ github.event.inputs.rom }}.png"
            if ! [ -f "${BANNER}" ]; then
                wget $BANNER_LINK -O $BANNER
                cd $HOME/logo
                ls -al
            fi
            TELEGRAM_FOLDER="${HOME}"/telegram
            if ! [ -d "${TELEGRAM_FOLDER}" ]; then
                git clone https://github.com/laityts/telegram.sh/ "${TELEGRAM_FOLDER}"
            fi
            TELEGRAM="${TELEGRAM_FOLDER}"/telegram
            tg_pub() {
                "${TELEGRAM}" -t "${{ secrets.TELEGRAM_TOKEN }}" -c "${{ secrets.CHATID }}" -i "$BANNER" -M \
                "$(
                               for POST in "${@}"; do
                                        echo "${POST}"
                               done
                )"
            }
            tg_pub "#ROM #${{ github.event.inputs.rom }} #${{ github.event.inputs.branch }} ${TREBLE}" \
                    "*${{ github.event.inputs.rom }} UnOfficial | Android 12*" \
                    " " \
                    "* • Device:* ${{ github.event.inputs.target }}" \
                    "* • Date:* ${{ steps.build.outputs.build_date }}" \
                    "* • Size:* ${{ steps.build.outputs.size }}" \
                    "* • MD5:* [Here](${{ steps.build.outputs.md5sum }})" \
                    "* • Changelogs:* [Here](https://github.com/laityts/ChangeLog/blob/${{ github.event.inputs.rom }}/changelog_${{ github.event.inputs.target }}.txt)" \
                    " " \
                    "*First time installation:*" \
                    " - Download ROM from below" \
                    " - Download Magisk for Android 12 (optionally)" \
                    " - Reboot to recovery" \
                    " - Format data (if encrypted)" \
                    " - Wipe system, vendor, cache, dalvik, data" \
                    " - Flash ROM zip and magisk (optional)" \
                    " - Flash latest miui firmware" \
                    " - Reboot" \
                    " " \
                    "*Dirty flash/Update:*" \
                    " - Wipe system, vendor, cache, dalvik" \
                    " - Flash ROM zip and magisk (optional)" \
                    " - Reboot"

      - name: ButtonUrl
        uses: ./
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          run: |
            echo "ButtonUrl"
            NAME="$(basename ${{ steps.build.outputs.filename }})"
            RELEASE="https://github.com/${{ github.repository }}/releases/tag/${{ github.run_id }}"
            curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
              -H "Content-Type: application/json" \
              -d '{
                     "chat_id": "'"${{ secrets.CHATID }}"'",
                     "text": "'"$NAME"'",
                     "reply_markup":
                     {
                         "inline_keyboard": [
                             [{
                                 "text": "Release",
                                 "url": "'"$RELEASE"'"
                             },
                             {
                                 "text": "WeTransfer",
                                 "url": "'"${{ steps.wetrans.outputs.wetransfer }}"'"
                             }]
                         ]
                     }
                 }'